export const allCmData = [
  {
    id: "1",
    us_dot: "123",
    company_name: "SSB",
    address: "Ololo",
    phone_number: "665 555 555 555",
    // status: "acive",
    status: "active",
    active_drivers: "198",
    actions: {
      open: "fa-solid fa-file-pen",
      status: "",
      delete: "fa-solid fa-trash",
    },
    actionsFncOpen: "setOpen(true)",
    actionsFncSts: "setOpenStatus(true)",
    actionsFncDlt: "setOpenDelete(true)",
  },
  {
    id: "2",
    us_dot: "1234",
    company_name: "Wake",
    address: "Osh",
    phone_number: "0554112233",
    // status: "inactive",
    status: "inactive",
    active_drivers: "198",
    actions: {
      open: "fa-solid fa-file-pen",
      status: "",
      delete: "fa-solid fa-trash",
    },
    actionsFncOpen: " setOpen(true)",
    actionsFncSts: " setOpenStatus(true)",
    actionsFncDlt: " setOpenDelete(true)",
  },
  {
    id: "3",
    us_dot: "12345",
    company_name: "New York",
    address: "Chicago IL",
    phone_number: "665 555 555 555",
    // status: "active",
    status: true,
    active_drivers: "198",
    actions: {
      open: "fa-solid fa-file-pen",
      status: "",
      delete: "fa-solid fa-trash",
    },
    actionsFncOpen: " setOpen(true)",
    actionsFncSts: " setOpenStatus(true)",
    actionsFncDlt: " setOpenDelete(true)",
  },
  {
    id: "4",
    us_dot: "1234567",
    company_name: "California",
    address: "Chicago IL",
    phone_number: "889 512 555 555",
    // status: "active",
    status: true,
    active_drivers: "198",
    actions: {
      open: "fa-solid fa-file-pen",
      status: "",
      // status: "fa-solid fa-toggle-off",
      delete: "fa-solid fa-trash",
    },
    actionsFncOpen: " setOpen(true)",
    actionsFncSts: " setOpenStatus(true)",
    actionsFncDlt: " setOpenDelete(true)",
  },
  {
    id: "5",
    us_dot: "123456",
    company_name: "Venture Motor Freight",
    address: "Chicago IL",
    phone_number: "775 555 555 555",
    // status: "inactive",
    status: false,
    active_drivers: "198",
    actions: {
      open: "fa-solid fa-file-pen",
      status: "",
      delete: "fa-solid fa-trash",
    },
    actionsFncOpen: " setOpen(true)",
    actionsFncSts: " setOpenStatus(true)",
    actionsFncDlt: " setOpenDelete(true)",
  },
];
//

// ?
// export const data = [
//   {
//     all: [
//       {
//         id: "1",
//         us_dot: "123",
//         company_name: "SSB",
//         address: "Ololo",
//         phone_number: "665 555 555 555",
//         // status: "acive",
//         status: "active",
//         active_drivers: "198",
//         actions: {
//           open: "fa-solid fa-file-pen",
//           status: "",
//           delete: "fa-solid fa-trash",
//         },
//         actionsFncOpen: "setOpen(true)",
//         actionsFncSts: "setOpenStatus(true)",
//         actionsFncDlt: "setOpenDelete(true)",
//       },
//     ],
//   },
//   {
//     sub: [
//       {
//         id: "1",
//         us_dot: "123",
//         company_name: "SSB",
//         address: "Ololo",
//         phone_number: "665 555 555 555",
//         // status: "acive",
//         status: "active",
//         active_drivers: "198",
//         actions: {
//           open: "fa-solid fa-file-pen",
//           status: "",
//           delete: "fa-solid fa-trash",
//         },
//         actionsFncOpen: "setOpen(true)",
//         actionsFncSts: "setOpenStatus(true)",
//         actionsFncDlt: "setOpenDelete(true)",
//       },
//     ],
//   },
// ];

// export const subData = [
//   {
//     id: "1",
//     us_dot: "12345",
//     company_name: "SSB",
//     phone_number: "665 555 555 555",
//     start_date: "23.03.2022",
//     current_active_drivers: "125",
//     payment_per_driver: "90",
//     invoice_date: "23.03.2022",
//     status: "active",
//     actions: "",
//   },
//   {
//     id: "2",
//     us_dot: "123456",
//     company_name: "SILA",
//     phone_number: "777 777 777",
//     start_date: "23.03.2022",
//     current_active_drivers: "125",
//     payment_per_driver: "90",
//     invoice_date: "23.03.2022",
//     status: "active",
//     actions: "",
//   },
// ];
